services:
  app:
    build: .
    container_name: workspaced
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: ['bun', 'start']

  postgres:
    image: postgres:17.5
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
