name: PR Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Lint and Build
    runs-on: ubuntu-latest

    # Only run if PR is from dev branch
    if: github.head_ref == 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun lint

      - name: Run build
        run: bun build

      - name: Validation successful
        run: echo "All checks passed successfully!"
